#!/usr/bin/env python

def output(yamlFormat, configuration, versionDifferences):
    """
    Output the version differences. 
    """
    
    #Output format done here:
    if not yamlFormat:
        print("=> Version Changes")
        for repository in configuration["Repositories"]:
            print("    => [" + repository + "] Version Changes")
            for packageName, packageVersions in versionDifferences[repository].items():
                print("        => %s-%s  ->  %s-%s" % (packageName, packageVersions[0], packageName, packageVersions[1]))
    else:
        #Output format in Yaml:
        #Repository
        #    - Package name
        #        -Manjaro Version
        #        -Arch Version
        print("""# Output generated by compare-mirrors
# 
# Author: Joshua Strot
# URL: https://github.com/joshuastrot/compare-mirrors

        """)
        
        
        for repository in configuration["Repositories"]:
            print(repository + ":")
            for packageName, packageVersions in versionDifferences[repository].items():
                print("    - " + packageName + ":")
                print("        - \"" + packageVersions[0] + "\"")
                print("        - \"" + packageVersions[1] + "\"")
